name: 'Slack Workflow Notification'
description: 'Send notifications to Slack about workflow runs'
inputs:
  github-token:
    description: 'Token for authenticating with the Github API'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js' # Built with @vercel/ncc: `ncc build index.js --license licenses.txt`
